FROM eclipse-temurin:25-jre AS builder
WORKDIR /build
COPY magpie-server/target/magpie-server-*.jar app.jar
RUN java -Djarmode=tools -jar app.jar extract --layers --application-filename app.jar --destination extracted

# ----------------------------------------------------------------------------------------------------

FROM eclipse-temurin:25-jre

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /app/config /app/logs \
    && chown 1000:1000 /app/config /app/logs

WORKDIR /app

COPY --chown=1000:1000 magpie-server/src/main/resources/application-sample.yml config/application.yml

COPY --from=builder --chown=1000:1000 /build/extracted/dependencies/ ./
COPY --from=builder --chown=1000:1000 /build/extracted/spring-boot-loader/ ./
COPY --from=builder --chown=1000:1000 /build/extracted/snapshot-dependencies/ ./
COPY --from=builder --chown=1000:1000 /build/extracted/application/ ./

USER 1000
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
