FROM eclipse-temurin:25-jre AS builder
WORKDIR /build
COPY magpie-server/target/magpie-server-*.jar app.jar
RUN java -Djarmode=tools -jar app.jar extract --layers --application-filename app.jar --destination extracted

# ----------------------------------------------------------------------------------------------------

FROM eclipse-temurin:25-jre

RUN groupadd --gid 900 app \
    && useradd --uid 900 --gid app --no-create-home app \
    && mkdir -p /app/config /app/logs \
    && chown app:app /app/config /app/logs

WORKDIR /app

COPY --chown=app:app magpie-server/src/main/resources/application-sample.yml config/application.yml

COPY --from=builder --chown=app:app /build/extracted/dependencies/ ./
COPY --from=builder --chown=app:app /build/extracted/spring-boot-loader/ ./
COPY --from=builder --chown=app:app /build/extracted/snapshot-dependencies/ ./
COPY --from=builder --chown=app:app /build/extracted/application/ ./

USER app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
